Repository UPB-FILS-SdE2/upb-fils-sde2.github.io, pull requests merged in 2024-02, with the labels that each got.

#6 Add labeler
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: workflow

#8 Fix labeler path for website
  .github/labeler.yml
Labels: workflow

#9 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: workflow

#12 Add homework placeholders
  docs/devoir/01.md
  docs/devoir/02.md
  docs/devoir/03.md
  docs/devoir/04.md
  docs/devoir/05.md
  docs/devoir/_category_.json
  docusaurus.config.ts
Labels: devoir

#14 Update license
  docusaurus.config.ts
Labels: website

#15 Add intro page
  docs/cours/_category_.json
  docs/devoir/_category_.json
  docs/intro/images/alexandru_radovici.jpg
  docs/intro/images/cristiana_andrei.jpg
  docs/intro/index.md
  docs/tp/01.md
  src/pages/index.tsx
Labels: website, devoir, cours, tp

#16 Add course 1
  docs/cours/01.md
  static/cours/sde2_1.pdf
Labels: website, cours

#19 Add social card
  docusaurus.config.ts
  static/img/docusaurus-social-card.jpg
  static/img/sde2_social_card.png
Labels: website

#17 Added TP01
  docs/tp/01.md
Labels: tp

#20 Fix TP01 header
  docs/tp/01.md
Labels: tp
